### ISSUE TITLE
backouts cause confusion

### ISSUE THREAD

**Issue by jcristau** [mozilla/crashstop#11]
e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1421313 was uplifted to beta in comment 23, then backed out in comment 24, so it's not in any beta build, but crashstop thinks it's in 58.0b11 and up.

**Comment by calixteman** [comment]
Fixed in: https://github.com/mozilla/crashstop/commit/d2f2eda009fc5ca4cfb4d103682359039f38447e
Thanks
