### ISSUE TITLE
Make crashtop show in the old Bugzilla layout

### ISSUE THREAD

**Issue by lizzard** [mozilla/crashstop#13]
Die-hard old Bugzilla layout user, I wonder if we can make the extension work with that layout too instead of only the modal layout?

**Comment by calixteman** [comment]
Yes we can ;)

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/crashstop/commit/5466098f2dbb891edabd39d5167748ce5bbff795

**Comment by lizzard** [comment]
I love it when "we" means "you". Thanks!!!! It looks great.
