### ISSUE TITLE
Support regex proto-signature

### ISSUE THREAD

**Issue by padenot** [mozilla/crashstop#17]
Example of a complicated query (BMO bug 1431604), and its associated [search url]: 

```
[@ .*"webrtc::internal::VideoReceiveStream::Stop".*"mozilla::WebrtcVideoConduit::StopReceiving".* ]
```

[search url]: https://crash-stats.mozilla.com/search/?proto_signature=%40.%2A%22webrtc%3A%3Ainternal%3A%3AVideoReceiveStream%3A%3AStop%22.%2A%22mozilla%3A%3AWebrtcVideoConduit%3A%3AStopReceiving%22.%2A&product=Firefox&platform=windows&process_type=content&date=%3E%3D2017-07-29T13%3A35%3A54.000Z&date=%3C2018-01-29T11%3A35%3A54.000Z&_sort=-date&_facets=signature&_facets=build_id&_facets=version&_facets=release_channel&_facets=proto_signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#crash-reports

**Comment by calixteman** [comment]
Fix in https://github.com/mozilla/crashstop/commit/2c6c169b45b3a825debc9286cbe971f7632fb93f
Don't hesitate to reopen if there are some issues.
