### ISSUE TITLE
Addon shows non-existent crashes on fennec

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/crashstop#20]
when looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1441598 with the addon installed it displays a number of crashes from fennec 59.0b3 - as far as i can tell, socorro doesn't contain any reports from this signature coming from users on android though.

![grafik](https://user-images.githubusercontent.com/1524147/36932783-e2ee13f8-1ece-11e8-9cc4-dfa18907ca9b.png)

**Comment by calixteman** [comment]
The big is fixed now. Don't hesitate to reopen if needed.
