### ISSUE TITLE
Make the crash data section collapsible

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/crashstop#22]
There are times when the crash data table can be very large and not a point of interest for that particular bug, so it would be nice if it could be easily collapsed out of view in those cases.

**Comment by calixteman** [comment]
Do you want we store the state of the visibility in localStorage ?

**Comment by rvandermeulen** [comment]
Totally up to you. I don't have a strong preference one way or another.

**Comment by calixteman** [comment]
The feature is available in version 0.2.3 so update your addon.
