### ISSUE TITLE
500 Internal server error for links on homepage to get data per signature/patch or bug

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/crashstop#29]
when visiting the https://crash-stop.herokuapp.com/ site, i'm getting a 500 Internal server error when attempting to visit the following links:
https://crash-stop.herokuapp.com/crashdata.html
https://crash-stop.herokuapp.com/bug.html

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/crashstop/commit/3f5ea0496d3198e7b10a9f331b08efbf82d86f9b.
