### ISSUE TITLE
signature escaping is insufficient

### ISSUE THREAD

**Issue by jcristau** [mozilla/crashstop#32]
marcia noticed that crash-stop doesn't work on https://bugzilla.mozilla.org/show_bug.cgi?id=1480432

The signature there is libstdc++.so@0x2fcf and the extension doesn't escape the "+" characters when making a request to crash-stop.herokuapp.com and so doesn't get any results back.

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/crashstop/commit/dd4a45b896c7d297e39748cacc39931ee118cf89
