### ISSUE TITLE
Apply new Bugzilla skin including Dark Mode

### ISSUE THREAD

**Issue by kyoshino** [mozilla/crashstop#36]
The Crash Stop table doesn’t look good in the Dark Mode being developed in https://github.com/mozilla-bteam/bmo/pull/1261. I’ll send a pull request to apply the new skin.

![Screen Shot 2019-05-03 at 16 43 55](https://user-images.githubusercontent.com/2929505/57164763-1a5f1500-6dc3-11e9-9a37-1146e836da97.png)

**Comment by calixteman** [comment]
@kyoshino, could you file a bug here instead: https://github.com/mozilla/crash-stop-addon ?

**Comment by kyoshino** [comment]
Can you archive this repository and add a link to crash-stop-addon? 😅
