### ISSUE TITLE
Please make startup crash more obvious

### ISSUE THREAD

**Issue by sylvestre** [mozilla/crashstop#5]
For example, Like the signature with a red background and "Startup crash" next to it.

**Comment by calixteman** [comment]
You can see the effect: https://bugzilla.mozilla.org/show_bug.cgi?id=1276488
![screenshot-2018-3-7 1276488 - xpcom startup crashes in nstarray_impl t appendelement t mozilla preferences addboolvarcache](https://user-images.githubusercontent.com/5641725/37096934-7a60de48-221a-11e8-91b6-fcc68dc8959e.png)
